<a href="https://colab.research.google.com/github/Zaniac25/mtarini_22_032/blob/main/practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list=[1,-3,20,40,18,6]
print("the list is",list)

for i in range(0,len(list)):
  for j in range(i+1,len(list)):
    if list[i]>=list[j]:
      list[i],list[j]=list[j],list[i]
print("the sorted list is",list)

the list is [1, -3, 20, 40, 18, 6]
the sorted list is [-3, 1, 6, 18, 20, 40]


In [ ]:
l1=[2,3,4,5,6]
l2=[7,8,9,10,11]
print("The two sorted lists are",l1,l2)

s1=len(l1)
s2=len(l2)


SyntaxError: unexpected character after line continuation character (<ipython-input-8-507723d58dda>, line 3)

In [ ]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim) #2
print(arr2.shape) #(2,4)


2
(2, 4)


In [ ]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim) #2
print(arr2.shape) #(2,4)
print(arr2)

2
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
data2=[[1,2,3,4]]
arr2=np.array(data2)
print(arr2.ndim) #2
print(arr2.shape) #(2,4)
print(arr2)

2
(1, 4)
[[1 2 3 4]]


In [ ]:
a=np.array([[0,1,2],[2,3,4]])
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
ar=np.zeros((2,3))
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar=np.ones((2,3))
ar

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ar=np.eye(2)
ar

array([[1., 0.],
       [0., 1.]])

In [ ]:
array=np.arange(0,20,3)
array

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
array=np.random.randint(0,10,(3,3))
array

array([[2, 3, 0],
       [8, 8, 1],
       [1, 1, 4]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


In [ ]:
def gcd_fun(x,y):
  if(y==0):
    return x
  else:
    return gcd_fun(y,x%y)
x=int(input("Enter first number:"))
y=int(input("Enter the second number:"))
num=gcd_fun(x,y)
print("gcd of two numbers is:")
print(num)


Enter first number:25
Enter the second number:36
gcd of two numbers is:
1


In [ ]:
# Python3 implementation of the approach

# Function to return the square root of
# a number using Newtons method
def squareRoot(n, l) :

    # Assuming the sqrt of n as n only
    x = n

    # To count the number of iterations
    count = 0

    while (1) :
        count += 1

        # Calculate more closed x
        root = 0.5 * (x + (n / x))

        # Check for closeness
        if (abs(root - x) < l) :
            break

        # Update root
        x = root

    return root

# Driver code
if __name__ == "__main__" :

    n = 327
    l = 0.00001

    print(squareRoot(n, l))

# This code is contributed by AnkitRai01

18.083141320025124


In [ ]:
def binary_search(list1,n):
  low=0
  high=len(list1-1)-1
  mid=0
    while low<=high:
      mid=(high+low)//2
    if list1 (mid)<n1:
